name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
      working-directory: example
      env:
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
    - run: yarn install
      working-directory: example
    - run: yarn install
      working-directory: example
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true